# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 - phpunit --configuration TestSuite/phpunit.xml --coverage-text --debug

after_script:
 - php vendor/bin/coveralls -v

notifications:
  email: false

